# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0
#
# A short description of the repository that will show up on GitHub
# :tyranno: description: ${project.description}
description: CI/CD example
# :tyranno: homepage: ${project.urls.Homepage}
homepage: https://github.com/dmyersturnbull/cicd
# :tyranno: topics: ${project.keywords}
topics:
  - ci
  - ci/cd
#
labels:
  - name: "breaking"
    description: "💥 Breaking change"
    color: "#000000"
  - name: "help needed"
    description: "👋 Help needed"
    color: "#40fa40"
  #- name: "bookmark"
  #  description: "🔖 Important for reference"
  #  color: "#ffff44"
  - name: "changelog: include"
    description: "🔔 Always include in the changelog"
    color: "#f0e6e6"
  - name: "changelog: exclude"
    description: "🔕 Always omit from the changelog"
    color: "#eeeeee"
  - name: "type: drop"
    description: "❌ Removal of a feature"
    color: "#090970"
  - name: "type: feature"
    description: "✨ Addition or modification of a feature"
    color: "#090970"
  - name: "type: security"
    description: "🔒️ Vulnerability fix/mitigation or hardening"
    color: "#090970"
  - name: "type: deprecation"
    description: "🗑️ Deprecation of a feature or component"
    color: "#090970"
  - name: "type: fix"
    description: "🐛 Bug fix, excluding security vulnerabilities"
    color: "#090970"
  - name: "type: performance"
    description: "⚡️ Code change that improves performance"
    color: "#090970"
  - name: "type: build"
    description: "🔧 Change to the build system or external dependencies"
    color: "#090970"
  - name: "type: docs"
    description: "📝 Change to documentation only"
    color: "#090970"
  - name: "type: refactor"
    description: "♻️ Code change that does not affect behavior"
    color: "#090970"
  - name: "type: test"
    description: "🚨 Addition or modification of tests"
    color: "#090970"
  - name: "type: cicd"
    description: "⚙️ Change to continuous integration and deployment (CI/CD)"
    color: "#090970"
  - name: "type: style"
    description: "🎨 Code change that does not affect the meaning of the code"
    color: "#090970"
  - name: "type: chore"
    description: "️🧹 Other type of change"
    color: "#090970"
  - name: "priority: 4-critical"
    description: "🟥 Must be fixed ASAP"
    color: "#ff6600"
  - name: "priority: 3-high"
    description: "🟧 Stalls work on the project or its dependents"
    color: "#cc9911"
  - name: " priority: 2-medium"
    description: "🟨 Does not block release/milestone but should be prioritized"
    color: "#cccc11"
  - name: "priority: 1-low"
    description: "🟩 Does not block release/milestone and can be done at any time"
    color: "#99dd00"
  - name: "state: ready for dev"
    description: "🏁 Ready for work"
    color: "#cccccc"
  - name: "state: blocked"
    description: "🚧 Blocked by another issue"
    color: "#aaaaaa"
  - name: "state: needs details"
    description: "🏷️ Needs more details before work can begin"
    color: "#888888"
  - name: "state: rejected"
    description: "✖️ Will not be worked on"
    color: "#f9f9f9"
  - name: "state: awaiting triage"
    description: "🚦 Awaiting triage"
    color: "#666666"
  - name: "effort: 1-easy"
    description: "1️⃣ Easy (t < 1 hr)"
    color: "#500050"
  - name: "effort: 2-moderate"
    description: "2️⃣ Moderate (1 hr ≤ t < 4 hr)"
    color: "#600040"
  - name: "effort: 3-hard"
    description: "3️⃣️ Hard (≥ 4 hours)"
    color: "#800020"
  - name: "multipart"
    description: "*️⃣ Organizes multiple sub-issues"
    color: "#800000"
  #- name: "scope: plugin"
  #  description: "🧩 Plugins"
  #  color: "#009000"
  #- name: "scope: i18n"
  #  description: "🌐 Internationalization"
  #  color: "#009000"
