plugins:
  - "prettier-plugin-toml"
  - "prettier-plugin-ini"
  - "prettier-plugin-properties"
  - "prettier-plugin-sh"
  - "prettier-plugin-sql"
  - "@prettier/plugin-xml"

formatter: sql-formatter
keywordCase: lower
logicalOperatorNewline: after
language: postgresql
