# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

build:
  environment:
    # :tyranno: python: '${.python-version-in-cicd}'
    python: "3.13.1"
    analysis:
checks:
  python:
    code_rating: true
    duplicate_code: true
