# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

build:
  environment:
    # :tyranno: python: '${.default-python-version}'
    python: '3.12.3'
  nodes:
    my-tests:
      dependencies:
        before:
          - "pip install 'hatchling~=1.25'"
    analysis:
checks:
  python:
    code_rating: true
    duplicate_code: true
