# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

build:
  environment:
    # :tyranno: python: "${.project.requires-python~.semver_max(@)~}"
    python: "3.11.4"
  nodes:
    my-tests:
      dependencies:
        before:
          - "pip install 'hatchling~=1.7'"
    analysis:
      tests:
        override:
          - py-scrutinizer-run
checks:
  python:
    code_rating: true
    duplicate_code: true
