services:
  web:
    build: .
    volumes:
      - .:/var/app/
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/app
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: .
          target: /var/app

  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo:/var/lib/mongodb

  elastic:
    image: elasticsearch:8.17.4
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  mongo:
  elastic:

networks:
  default:
    enable_ipv6: true
