services:
  web:
    build: .
    volumes:
      - .:/var/lib/app/
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - POSTGRES_URI=postgres://user:password@postgres:5432/app
      - MONGO_URI=mongodb://mongodb:27017/app
    depends_on:
      - mongodb
      - postgres
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/0-init.sql # bind mount

  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo:/var/lib/mongodb

  elastic:
    image: elasticsearch:8.17.1
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  postgres:
  mongo:
  elastic:

networks:
  default:
    enable_ipv6: true
