# :tyranno: site_name: "${project.name}"
site_name: "CICD"

# :tyranno: site_name: "${.copyright}"
copyright: Copyright 2023 Contributors to the CICD project
# :tyranno: site_name: "${project.description}"
site_description: "CI/CD example"

# Navigation menu
nav:
  - Home: index.md
  - Introduction: intro.md
  - API: ref.md

# Theme
theme:
  name: material
  features:
    - tabs
  icon:
    logo: material/cloud
  font:
    text: Ubuntu
    code: Ubuntu Mono
  static_templates:
    - 404.html

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - smarty

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
