# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: lint-helm-charts
description: Lints Helm charts.

inputs:
  ref:
    required: true
    description: The ref of a branch, tag, or hash.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - uses: astral-sh/setup-uv@v6 # Some subsequent tools expect Python.
      with:
        activate-environment: true
    - uses: azure/setup-helm@v4.2.0
      with:
        version: v3.17.0
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.7.0
    - name: Run chart-testing (ct lint)
      shell: bash
      run: ct lint
