# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: "💬 Question"
description: "Question"
labels:
  - "type: question"
  - "state: awaiting triage"

body:
  - type: textarea
    id: text
    attributes:
      label: What question do you have?
      render: markdown
    validations:
      required: true
