# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow: that uploads `dist/` as GH workflow artifact `dist-${{ github.ref_name }}`.

# See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does
# See "Accessing contextual information about workflow runs".

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch or tag; for testing a PR, this should be the merge commit.
      ref_name:
        type: string
        required: true
        description: The name of the branch or tag.
      retention-days:
        type: number
        default: 1
        description: If > 0, uploads the zip file as GitHub artifact 'dist-<REF>' with this retention time.
      use-uv-sources:
        type: boolean
        default: false
        description: Use 'tool.uv.sources'; otherwise, passes '--no-sources' to 'uv build'.

env:
  ARTIFACT_NAME: dist-${{ inputs.ref_name }}
  UV_BUILD_OPTION: ${{ inputs.use-uv-sources && '' || '--no-sources' }}

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Build sources and wheels
        run: |
          uv build $UV_BUILD_OPTION
      - if: ${{ inputs.retention-days > 0 }}
        name: Upload 'dist/' (wheels and sdists) as artifact '${{ env.ARTIFACT_NAME }}'
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/
          if-no-files-found: error
          compression-level: 0 # they're already gzip-compressed
          retention-days: ${{ inputs.retention-days }}
      - name: Print artifact info
        run: |
          printf \
            "Uploaded artifact '%s':\n  ID: %s\nURI: %s\nDigest: %s\n" \
            "$ARTIFACT_NAME \
            "${{ steps.upload.outputs.artifact-id }}"
            "${{ steps.upload.outputs.artifact-url }}"
            "${{ steps.upload.outputs.artifact-digest }}"
