# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow: that runs `uv lock --upgrade`, commits, and pushes.

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch or tag; for a PR, this must be the head ref.

env:
  LOCK_COMMIT_MSG: "build: update lock file"
  PRECOMMIT_COMMIT_MSG: "ci: upgrade pre-commit config"
  UV_NO_SYNC: true

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]' || exit $?
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' || exit $?
      - name: Upgrade the lock file
        id: lock
        run: |
          uv lock --upgrade || exit $?
          git diff --quiet uv.lock || echo "has-changes=true" >> $GITHUB_OUTPUT
      - if: ${{ steps.lock.outputs.has-changes }}
        name: Commit uv.lock changes
        run: |
          git commit --no-verify -m "$LOCK_COMMIT_MSG" uv.lock || exit $?
      - name: Upgrade the pre-commit config
        id: precommit
        run: |
          uv sync --frozen --only-group precommit || exit $?
          uv run pre-commit install || exit $?
          uv run pre-commit autoupdate || exit $?
          git diff --quiet .pre-commit-config.yaml || echo "has-changes=true" >> $GITHUB_OUTPUT
      - if: ${{ steps.precommit.outputs.has-changes }}
        name: Commit pre-commit changes
        run: |
          git commit --no-verify -m "PRECOMMIT_COMMIT_MSG" .pre-commit-config.yaml || exit $?
      - if: ${{ steps.lock.outputs.has-changes || steps.precommit.outputs.has-changes }}
        name: Push changes
        run: |
          git push || exit $?
