# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow: that runs `uv lock --upgrade`, commits, and pushes.
run-name: Bump deps on ${{ inputs.ref || 'Îµ' }}

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch, tag, or hash; for a PR, this must be the head ref.

concurrency:
  group: _bump-deps / ${{ inputs.ref }}
  # There are no parameters to worry about potentially conflicting,
  # and there's a single (atomic) push -- so we're ok to cancel.
  # The only caveat is that some bump runs could be skipped.
  cancel-in-progress: true

env:
  LOCK_COMMIT_MSG: "build: update lock file"
  PRECOMMIT_COMMIT_MSG: "ci: upgrade pre-commit config"

defaults:
  run:
    shell: bash

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Upgrade the lock file
        id: lock
        run: |
          uv lock --upgrade
          git diff --quiet uv.lock || echo "has-changes=true" >> $GITHUB_OUTPUT
      - if: ${{ steps.lock.outputs.has-changes }}
        name: Commit uv.lock changes
        run: |
          git commit --no-verify -m "$LOCK_COMMIT_MSG" uv.lock
      - name: Upgrade the pre-commit config
        id: precommit
        run: |
          uv sync --frozen --only-group precommit
          uv run pre-commit install
          uv run pre-commit autoupdate
          git diff --quiet .pre-commit-config.yaml || echo "has-changes=true" >> $GITHUB_OUTPUT
      - if: ${{ steps.precommit.outputs.has-changes }}
        name: Commit pre-commit changes
        run: |
          git commit --no-verify -m "PRECOMMIT_COMMIT_MSG" .pre-commit-config.yaml
      - if: ${{ steps.lock.outputs.has-changes || steps.precommit.outputs.has-changes }}
        name: Push changes
        run: |
          git push
