# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that lints with Ruff.

on:
  workflow_call:
    inputs:
      rules:
        type: string
        default: ""
      glob:
        type: string
        default: .

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Check Ruff formatting
        run: |
          uv run --locked ruff format --exit-non-zero-on-format ${{ inputs.glob }} || exit $?
      - name: Check Ruff rules
        run: |
          if [[ -z "${{ inputs.rules }}" ]]; then
            uv run --locked ruff check --no-fix ${{ inputs.glob }} || exit $?
          else
            uv run --locked ruff check --select "${{ inputs.rules }}" --no-fix ${{ inputs.glob }} || exit $?
          fi
