# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that checks we can build the docs.
run-name: Check docs on ${{ inputs.ref || 'Îµ' }}

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch, tag, or hash; for a PR, this should be the merge commit.
      cancel-in-progress:
        type: boolean
        description: >-
          Cancel already-running runs for the same ref.
          Enable for ad-hoc checks, but keep disabled otherwise.
          This is important if 'ref' is an "abbreviated ref" rather than a hash.

concurrency:
  group: _check-docs / ${{ inputs.ref }}
  cancel-in-progress: ${{ inputs.cancel-in-progress }}

defaults:
  run:
    shell: bash

jobs:
  check-mkdocs:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked --only-group docs
          uv run mkdocs build --strict
