# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that checks we can build the docs.

on:
  workflow_call:
    inputs:
      ref:
        type: string

jobs:
  check-mkdocs:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked --only-group docs || exit $?
          uv run mkdocs build --strict || exit $?
