# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that checks basic things via pre-commit hooks.

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch or tag; for a PR, this should be the head ref.

env:
  UV_NO_SYNC: true

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR's HEAD (not merge commit)
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Run some pre-commit hooks
        run: |
          uv sync --frozen --only-group precommit || exit $? # Sync and confirm lock file is up-to-date.
          chk() {
            uv run pre-commit run --all-files $1 || exit $?
          }
          chk check-added-large-files
          chk forbid-new-submodules
          chk check-case-conflict
          chk check-illegal-windows-names
          chk check-merge-conflict
          chk check-symlinks
          # These auto-fix, but we're not committing the changes:
          chk fix-byte-order-marker
          chk end-of-file-fixer
          chk trailing-whitespace
