# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that lints with Ruff.

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch, tag, or hash; for a PR, this should be the head ref.
      rules:
        type: string
        default: ""
        description: Ruff rule specifier passed as 'ruff check --select <rules>'.
      glob:
        type: string
        default: .
        description: Glob pattern of paths passed as 'ruff check <glob>'.

defaults:
  run:
    shell: bash

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked --only-group ruff
      - name: Check Ruff rules
        run: |
          if [[ -z '${{ inputs.rules }}' ]]; then
            uv run ruff check --no-fix '${{ inputs.glob }}'
          else
            uv run ruff check --no-fix --select '${{ inputs.rules }}' ${{ inputs.glob }}'
          fi
      - name: Check Ruff formatting
        run: |
          uv run ruff format --check ${{ inputs.glob }}'
