# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that lints with Ruff.

on:
  workflow_call:
    inputs:
      rules:
        type: string
        default: ""

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: |
          if [[ -z "${{ inputs.rules }}" ]]; then
            uv run --locked ruff check --no-fix . || exit $?
          else
            uv run --locked ruff check --select "${{ inputs.rules }}" --no-fix . || exit $?
          fi
