# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that checks basic things via pre-commit hooks.
run-name: Check hooks on ${{ inputs.ref || 'Îµ' }}

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch, tag, or hash; for a PR, this should be the head ref.
      cancel-in-progress:
        type: boolean
        description: >-
          Cancel already-running runs for the same ref.
          Enable for ad-hoc checks, but keep disabled otherwise.
          This is important if 'ref' is an "abbreviated ref" rather than a hash.
      check-schemas:
        type: boolean
        default: false
        description: Also validate schemas.

concurrency:
  group: _check-hooks / ${{ inputs.ref }} / ${{ inputs.check-schemas }}
  # Separating by `check-schemas` is a little weird,
  # but it's the easiest way to prevent a non-schema-check run from cancelling a schema-check run.
  # Otherwise, we'd need to use `${{ cancel-in-progress || inputs.check-schema }}`,
  # which would be surprising.
  cancel-in-progress: ${{ cancel-in-progress }}

defaults:
  run:
    shell: bash

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    env:
      CHECK_SCHEMAS: ${{ inputs.check-schemas && 'true' || 'false' }}
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - name: Run some pre-commit hooks
        run: |
          uv sync --frozen --only-group precommit # Sync and confirm lock file is up-to-date.
          chk() {
            uv run pre-commit run --all-files $1
          }
          chk check-added-large-files
          chk forbid-new-submodules
          chk check-case-conflict
          chk check-illegal-windows-names
          chk check-merge-conflict
          chk check-symlinks
          # These auto-fix, but we're not committing the changes:
          chk fix-byte-order-marker
          chk end-of-file-fixer
          chk trailing-whitespace
          if [[ "$CHECK_SCHEMAS" == true ]]; then
            chk check-github-workflows
            chk check-compose-spec
          fi
