# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

name: Deploy docs

on:
  push:
    branches:
      - main
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Deploy latest docs
        if: ${{ github.ref_name == 'main' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          pip install hatch
          hatch run deploy-docs --update-aliases latest --push
      - name: Deploy docs for ${{ github.ref_name }}
        if: ${{ github.ref_type == 'tag' }}
        run: |
          pip install hatch
          hatch run deploy-docs ${{ github.ref_name }} --push
      - name: Publish GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: site
          # Write .nojekyll at the root, see:
          # https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators
          enable_jekyll: false
          # Only deploy if there were changes
          allow_empty_commit: false
