# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

name: Deploy docs

on:
  push:
    branches:
      - main
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Deploy latest docs
        if: ${{ github.ref_name == 'main' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          pip install hatch
          hatch run deploy-docs --update-aliases latest --push
      - name: Deploy docs for ${{ github.ref_name }}
        if: ${{ github.ref_type == 'tag' }}
        run: |
          pip install hatch
          hatch run deploy-docs ${{ github.ref_name }} --push
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
