# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that lints with Ruff, YAML, and others.

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch, tag, or hash; for a PR, this should be the head ref.
      tasks:
        type: string
        default: python,dockerfile,yaml,charts
        description: Comma-separated list of 'python', 'dockerfile', 'yaml', 'charts'.
      rules:
        type: string
        default: ""
        description: Ruff rule specifier passed as 'ruff check --select <rules>'.
      glob:
        type: string
        default: .
        description: Glob pattern of paths.

defaults:
  run:
    shell: bash

jobs:
  lint-ruff:
    if: ${{ contains(inputs.tasks, 'python') }}
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked --only-group ruff
      - name: Check Ruff rules
        run: |
          if [[ -z '${{ inputs.rules }}' ]]; then
            uv run ruff check --no-fix '${{ inputs.glob }}'
          else
            uv run ruff check --no-fix --select '${{ inputs.rules }}' ${{ inputs.glob }}'
          fi
      - name: Lint Ruff formatting.
        run: |
          uv run ruff format --check '${{ inputs.glob }}'
      - id: has-deal
        run: |
          uv run python -m deal --help >> /dev/null \
            && echo "has_deal=true" >> "$GITHUB_OUTPUT"
      - if: ${{ steps.has-deal.outputs.has_deal }}
        name: Check Deal rules
        run: |
          uv run python -m deal lint '${{ inputs.glob }}'

  lint-dockerfile:
    if: ${{ contains(inputs.tasks, 'dockerfile') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      # hadolint's last release was in 2022.
      # However, it's decidedly not abandoned: https://github.com/hadolint/hadolint/issues/1041
      # It's also so widely used that it will find a new maintainer if needed.
      # Unfortunately, some issues aren't being fixed.
      - name: Temporary hadolint workaround
        run: sed 's/\--start-interval=1s //g' Dockerfile > .~hadolint.temp~
      - uses: hadolint/hadolint-action@v3.1.0 # Currently doesn't publish e.g. `v3`.
        with:
          dockerfile: .~hadolint.temp~
      - if: ${{ always() }}
        run: |
          rm -r -f .~hadolint.temp~

  lint-yaml:
    if: ${{ contains(inputs.tasks, 'yaml') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Lint for serious issues in YAML files.
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          file_or_dir: "${{inputs.glob}}"
          # Only lint real issues, not formatting.
          config_data: |
            rules:
              anchors:
                forbid-undeclared-aliases: true
                forbid-duplicated-anchors: true
                forbid-unused-anchors: true
              float-values:
                require-numeral-before-decimal: true
                forbid-scientific-notation: true
                forbid-nan: true
                forbid-inf: true
              key-duplicates:
                forbid-duplicated-merge-keys: true
              octal-values:
                forbid-implicit-octal: true
                forbid-explicit-octal: true
              truthy:
                allowed-values:
                  - true
                  - false

  lint-helm:
    if: ${{ contains(inputs.tasks, 'charts') }}
    name: Lint Helm charts.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6 # Some subsequent tools expect Python.
        with:
          activate-environment: true
      - uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Run chart-testing (lint)
        run: ct lint
