# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that publishes a release to PyPI.
# Always uses ${{ github.ref }}
# Requires `_build_dist.yaml`.
run-name: Publish ${{ github.ref }} to ${{ inputs.repository }}

concurrency:
  group: _publish-pypi / ${{ inputs.ref }}
  # Per the logic in `_publish-docker.yaml`, we should always cancel.
  # The publish step is atomic, so it's safe to do this.
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
        description: Either 'pypi' or 'testpypi'.

env:
  ARTIFACT_NAME: dist-${{ github.ref_name }}
  PYPI_TARGET: >-
    ${{
      inputs.repository == 'pypi'
        && 'https://upload.pypi.org/legacy/'
        || 'https://test.pypi.org/legacy/'
    }}

defaults:
  run:
    shell: bash

jobs:
  publish-pypi:
    # This job publishes the package to PyPI.
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Download dist/ GH workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Publish to PyPi using uv.
        # See: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
        run: |
          uv publish --publish-url "$PYPI_TARGET" --trusted-publishing always
