# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that builds a Docker image and publishes it to container registries.

on:
  workflow_call:

jobs:
  publish-docker:
    name: Publish to container registries
    runs-on: ubuntu-latest
    env:
      image_name: ${{ GITHUB_REPOSITORY }} # Assume the image is `owner/repo`
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: Extract Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5 # https://github.com/docker/metadata-action
        with:
          images: ${{ env.image_name }}
      - name: Print metadata
        run: |
          printf "Docker metadata:\n%s\n" "${{ steps.docker-metadata.outputs.json }}"
      # Help for specific registries at https://github.com/docker/login-action
      - name: Log into Docker Hub
        if: ${{ vars.DOCKERHUB_USERNAME }} # True if it's **defined**
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log into GHCR
        if: ${{ inputs.to-ghcr }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }} # For GHCR, this is probably ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the image to configured registries
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          # type=gha,mode=max is meant to maximize cache hits.
          cache-to: type=gha,mode=max
