# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that builds docs and deploys them to GitHub Pages.
# Always uses ${{ github.ref }}.

on:
  workflow_call:

env:
  UV_NO_SYNC: true

jobs:
  publish-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked --only-group docs || exit $?
          uv run mkdocs build --strict || exit $?
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .site
      - uses: actions/deploy-pages@v4
