# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that builds a Docker image and publishes it to container registries.
# Always uses ${{ github.ref }}.

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: true
        description: Push to container registries; otherwise, only performs a dry run.

env:
  IMAGE_NAME: ${{ github.repository }} # Assume the image is `owner/repo`

jobs:
  publish-docker:
    name: Publish to container registries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Extract Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5 # https://github.com/docker/metadata-action
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Print metadata
        env:
          METADATA: ${{ steps.docker-metadata.outputs.json }}
        run: |
          printf "Docker metadata:\n%s\n" "$METADATA"
      # Help for specific registries at https://github.com/docker/login-action
      - if: ${{ vars.DOCKERHUB_USERNAME != '' }} # True if it's **defined**
        name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: ${{ vars.GHCR_USERNAME != '' }}
        name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }} # For GHCR, this is probably ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the image to configured registries
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          # type=gha,mode=max is meant to maximize cache hits.
          cache-to: type=gha,mode=max
          push: ${{ inputs.push }}
