# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that publishes a release to GitHub and creates alias Git tags like `v1`.
# Always uses ${{ github.ref }}
# Requires `_build_dist.yaml`.

on:
  workflow_call:

env:
  ARTIFACT_NAME: dist-${{ github.ref_name }}
  IS_LATEST: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}

defaults:
  run:
    shell: bash

jobs:
  tag-latest:
    # This job tags the release as 'latest' and 'v<x>', where <x> is its major version
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: ${{ env.IS_LATEST }}

  publish-github:
    runs-on: ubuntu-latest
    steps:
      - name: Download dist/ GH workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Publish to GitHub Releases
        id: release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: dist/*
      - name: Print info
        env:
          RELEASE_URL: ${{ steps.release.outputs.url }}
        run: |
          printf "Published release: %s\n" "$RELEASE_URL"
