# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that builds docs and deploys them to GitHub Pages.
run-name: Publish docs for ${{ github.ref }}

on:
  workflow_call:

concurrency:
  group: _publish-docs / ${{ inputs.ref }}
  # Per the same logic in `_publish-docker.yaml`, we should always cancel;
  # this applies whether we have versioned or unversioned docs.
  # This isn't atomic, but `upload-pages-artifact` replaces any previous files -- so we're ok.
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  publish-mkdocs:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync --locked --only-group docs
          uv run mkdocs build --strict
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .site
      - uses: actions/deploy-pages@v4
