# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that runs `_run-pytest-single` for each OS and Python version.

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The branch or tag
      markers:
        type: string
        default: not ux
      retention-days:
        type: number
        default: 0

env:
  REF: ${{ inputs.ref || github.ref_name }}

jobs:
  run-tests:
    name: Test ${{ env.REF }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          # :tyranno-start: $<<.python-versions|yaml_long(@)>>
          - "3.13"
          # :tyranno-end
    uses: ./.github/workflows/_run-pytest-single.yaml
    with:
      ref: ${{ env.REF }}
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      retention-days: ${{ inputs.retention-days }}
      markers: ${{ inputs.markers }}
