# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that runs `_run-pytest-single` for each OS and Python version.
# See:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The branch, tag, or hash; for a PR, this should be the merge commit.
      markers:
        type: string
        default: not ux
      retention-days:
        type: number
        default: 0
        description: If > 0, uploads coverage reports 'coverage-<ref>-<os>-<python>', using this retention time.
      fail-fast:
        type: boolean
        default: true
        description: >-
          Fail this workflow immediately when any test on any OS and Python version fails.
          Applies 'fast-fail' to the strategy, and runs pytest with '--exitfirst'.
          Recommended when only confirming that tests pass, such as immediately before publishing or reporting coverage.
      max-parallel:
        type: number
        default: 1
        description: Increase when testing important branches; leave at 1 for PRs.

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    name: Test ${{ inputs.ref }}
    strategy:
      fail-fast: ${{ inputs.fail-fast }} # Doesn't affect the status of the `run-tests` job.
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          # ::tyranno-start:: $<<~.cicd.python."minor-versions-to-test">>
          - "3.13"
          # :tyranno-end
    uses: ./.github/workflows/_run-pytest-single.yaml
    with:
      ref: ${{ inputs.ref }}
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      retention-days: ${{ inputs.retention-days }}
      markers: ${{ inputs.markers }}
      fail-fast: ${{ inputs.fail-fast }}
