# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:
    inputs:
      store-coverage:
        type: boolean
        default: false
      markers:
        type: string
        default: not ux

jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }}, Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          # :tyranno-start: ${{.python-versions}}|yaml_long(@)
          - "3.13"
          # :tyranno-end
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ matrix.python }}"
      - name: Install dependencies and run tests
        run: |
          uv run --locked pytest -m "${{ inputs.markers }}" || exit $?
      - name: Store coverage reports
        if: ${{ inputs.store-coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python }}
          path: coverage.json
          if-no-files-found: error
