# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that runs `_run-pytest-single` for each OS and Python version.

on:
  workflow_call:
    inputs:
      store-coverage:
        type: boolean
        default: false
      markers:
        type: string
        default: not ux

jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }}, Python ${{ matrix.python }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          # :tyranno-start: $<<.python-versions|yaml_long(@)>>
          - "3.13"
          # :tyranno-end
    uses: ./.github/workflows/_run-pytest-single.yaml
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      store-coverage: ${{ inputs.store-coverage }}
      markers: ${{ inputs.markers }}
