# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that runs pytest for a single OS and Python version.
# Normally run by `_run-pytest`.

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      os:
        type: string
        required: true
      python:
        type: string
        required: true
      markers:
        type: string
        default: not (ux or e2e)
      retention-days:
        type: number
        default: 0
      fail-fast:
        type: boolean
        default: false

env:
  MARKERS: ${{ inputs.markers || 'not (ux or e2e)' }}
  PYTEST_ARGS: ${{ inputs.fast-fail && '--exitfirst' || '' }}

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    name: Test ${{ inputs.ref }} on ${{ inputs.os }}, Python ${{ inputs.python }}
    runs-on: ${{ inputs.os }}
    env:
      UV_NO_SYNC: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "${{ inputs.python }}"
      - name: Install dependencies and run tests
        run: |
          uv sync --locked --exact --no-dev --group test
          # shellcheck disable=SC2086 # Intentionally word-split into an array.
          read -r -a pytest_args <<< "$PYTEST_ARGS"
          uv run pytest -m "$MARKERS" "${pytest_args[@]}"
      - if: ${{ inputs.retention-days > 0 }}
        name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ inputs.ref }}-${{ inputs.os }}-${{ inputs.python }}
          include-hidden-files: true
          path: .coverage.json
          compression-level: 8 # highly compressible
          if-no-files-found: error
          retention-days: ${{ inputs.retention-days }}
