# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that syncs some GitHub repo metadata to `.github/project.yaml`.

on:
  workflow_call:

env:
  SETTINGS_PATH: .github/project.yaml

defaults:
  run:
    shell: bash

jobs:
  sync-repo-metadata:
    runs-on: ubuntu-latest
    env:
      # For historical reasons, the GH CLI uses GH_TOKEN instead of GITHUB_TOKEN
      # https://github.com/github/docs/issues/21930
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Install jq and yq
        run: sudo snap install jq yq
      - name: Set repo metadata
        run: |
          # Read the metadata
          description=$(yq eval '.description' "$SETTINGS_PATH")
          homepage=$(yq eval '.homepage' "$SETTINGS_PATH")
          topics=$(yq eval '.topics | join(",")' "$SETTINGS_PATH")
          # Update the repo metadata.
          gh repo edit $GITHUB_REPOSITORY \
            --description "$description" \
            --homepage "$homepage" \
            --add-topic "$topics"
          printf "Updated repo description, homepage, and topics.\n"
