# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Tests building images on Ubuntu and Windows.
run-name: Test ${{ inputs.ref }} Docker

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The ref of a branch, tag, or hash.

jobs:
  build-images:
    name: Test building image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # Don't test macOS because we'd need to set up Docker.
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: astral-sh/setup-uv@v6
      - run: |
          shell: bash
          docker build .
