# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that sends code coverage reports to Codecov.
# Requires `_run-pytest.yaml` and the secret `CODECOV_TOKEN`.

on:
  workflow_call:

jobs:
  send:
    name: Send reports to codecov
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python:
          # :tyranno-start: $<<.cicd.python-versions|yaml_long(@)>>
          - "3.13"
          # :tyranno-end:
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
      ARTIFACT_NAME: coverage-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.python }}
    steps:
      - name: Download workflow artifact ${{ env.ARTIFACT_NAME }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Upload coverage report ${{ env.ARTIFACT_NAME }} to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./.coverage.json
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
