# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Sends code coverage reports to Coveralls.
# Generates and sends reports for multiple OSes and Python versions.
# YOU MUST FIRST RUN`_run-pytest`.

on:
  workflow_call:

jobs:
  send-to-coveralls:
    name: Send reports to Coveralls
    runs-on: ${{ matrix.os }}
    strategy:
      # Use a matrix to send OS-specific and Python-version-specific coverage data.
      matrix:
        os:
          - ubuntu-latest
        python:
          # :tyranno-start: $<<.cicd.python-versions|yaml_long(@)>>
          - "3.13"
          # :tyranno-end:
    steps:
      - name: Determine whether this is the last report.
        id: last-report
        shell: bash
        run: |
          echo "is_last_report=(( ${{ strategy.job-index }} == ${{ strategy.job-total }} - 1 ))" \
            >> "$GITHUB_OUTPUT" \
            || exit $?
      - name: Download coverage artifact for ${{ matrix.os }} / Python ${{ matrix.python }}
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python }}
      - name: Send coverage report for ${{ matrix.os }}-${{ matrix.python }} to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ matrix.os }}-py${{ matrix.python }}
          parallel: true
          parallel-finished: ${{ env.is_last_report }}
