# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Sends code coverage reports to Codecov.
# Generates and sends reports for multiple OSes and Python versions.
# YOU MUST FIRST RUN`_run-pytest`.
# You must also provide the secret CODECOV_TOKEN that Codecov generates.

on:
  workflow_call:

jobs:
  send-to-codecov:
    name: Send reports to codecov
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python:
          # :tyranno-start: $<<.cicd.python-versions|yaml_long(@)>>
          - "3.13"
          # :tyranno-end:
    steps:
      - name: Send coverage report for ${{ matrix.os }}-${{ matrix.python }} to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: matrix.os,matrix.python
          fail_ci_if_error: true

  finalize-codecov-send:
    # This job sends final data to Coveralls to mark the parallel runs as finished.
    # Will not run if the 'send-to-codecov' job was not cancelled.
    needs: send-to-codecov
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send final data to Coveralls to mark the set completed
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          file: .coverage.json
