# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that sends code coverage reports to Coveralls.
# Requires `_run-pytest.yaml` and the secret `COVERALLS_TOKEN`.
on:
  workflow_call:

jobs:
  send:
    name: Send reports to Coveralls
    runs-on: ${{ matrix.os }}
    strategy:
      # Use a matrix to send OS-specific and Python-version-specific coverage data.
      matrix:
        os:
          - ubuntu-latest
        python:
          # ::tyranno-start:: $<<~.cicd.python."minor-versions-to-test">>
          - "3.13"
          # ::tyranno-end::
    env:
      artifact_name: coverage-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.python }}
    steps:
      - name: Download workflow artifact ${{ env.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name }}
      - name: Send coverage report ${{ env.artifact_name }} to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ matrix.os }}-py${{ matrix.python }}
          parallel: true
  finish:
    needs: send
    name: Tell Coveralls the reports were all sent
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
