# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Reusable workflow that sends code coverage reports to Coveralls.
# Requires `dist-` artifacts and the secret `COVERALLS_TOKEN`.
run-name: Send ${{ inputs.ref_name }} Coveralls report

on:
  workflow_call:
    inputs:
      ref_name:
        type: string
        required: true
        description: The name of the branch or tag.

concurrency:
  group: _update-coveralls / ${{ inputs.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  send:
    name: Send reports to Coveralls
    runs-on: ${{ matrix.os }}
    strategy:
      # Use a matrix to send OS-specific and Python-version-specific coverage data.
      matrix:
        os:
          - ubuntu-latest
        python:
          # ::tyranno start:: $<<~.python."test-versions">>
          - "3.13"
          # ::tyranno end::
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
      ARTIFACT_NAME: coverage-${{ inputs.ref_name }}-${{ matrix.os }}-${{ matrix.python }}
    steps:
      - name: Download workflow artifact ${{ env.ARTIFACT_NAME }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Send coverage report ${{ env.ARTIFACT_NAME }} to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ env.OS }}-py${{ env.PYTHON }}
          parallel: true

  finish:
    needs: send
    name: Tell Coveralls the reports were all sent
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
