# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# "Function" workflow that sends code coverage reports to Codecov.
# Requires `_run-pytest.yaml` and the secret `CODECOV_TOKEN`.

on:
  workflow_call:

jobs:
  send:
    name: Send reports to codecov
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python:
          # ::tyranno-start:: $<<.cicd.python-versions|yaml(@)>>
          - "3.13"
          # ::tyranno-end::
    env:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      artifact_name: coverage-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.python }}
    steps:
      - name: Download workflow artifact ${{ env.artifact_name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name }}
      - name: Upload coverage report ${{ env.artifact_name }} to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: os,python
          fail_ci_if_error: true
          files: ./.coverage.json
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
