# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Checks for security vulnerabilities on PRs.

on:
  pull_request:
    types:
      - review_requested
    paths:
      - src/**/*.py
      - tests/**/*.py
      - pyproject.toml

permissions:
  contents: read

jobs:
  audit:
    uses: ./.github/workflows/_check-ruff.yaml
    with:
      rules: S
