# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Responds to "command" comments on pull requests.

on:
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read

jobs:
  audit:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-audit') }}
    uses: ./.github/workflows/_check-ruff.yaml
    with:
      rules: S

  lint:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-lint') }}
    uses: ./.github/workflows/_check-ruff.yaml

  check-docker:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-check-docker') }}
    uses: ./.github/workflows/_reformat.yaml

  check-docs:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-check-docs') }}
    uses: ./.github/workflows/_check-mkdocs.yaml

  upgrade:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-upgrade') }}
    permissions:
      contents: write
    uses: ./.github/workflows/_bump-deps.yaml

  reformat:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-reformat') }}
    permissions:
      contents: write
    uses: ./.github/workflows/_reformat.yaml

  test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-test') }}
    uses: ./.github/workflows/_run-pytest.yaml

  unit-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/please-unit-test') }}
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      markers: not (ux or slow or net)
