# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

name: Bump version
# Manually called workflow that uses Commitizen to bump the version.
# Adds a commit like 'bump:

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: choice
        required: true
        description: Pre-release type
        options:
          - alpha
          - beta
          - rc
          - none

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  bump:
    name: Bump version with commitizen
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set prerelease type from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "prerelease=${{ github.event.inputs.prerelease }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - id: cz-release
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@v0.2
        with:
          github_token: ${{ secrets.github_token }}
          git_name: ${{ steps.gpg.outputs.name }}
          git_email: ${{ steps.gpg.outputs.email }}
          gpg_sign: true
          prerelease: ${{ env.prerelease }}
          changelog: false
          debug: true

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz-release.outputs.version }}"
