# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: check-security
run-name: >
  ${{ github.workflow }} \
  ${{ github.ref_name }} \
  (triggered by ${{ github.ref_type }})

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - edited
    paths:
      - "**/*.py"
      - pyproject.toml
  issue_comment:
    types:
      - created

permissions:
  contents: read
  statuses: write
  actions: read
  security-events: write

jobs:
  security:
    name: Run security linters
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request'
      && (
        github.event.action == 'ready_for_review'
        || github.event.pull_request.draft == false
        && (
          github.event.action == 'opened'
          || github.event.action == 'edited'
          || github.event.action == 'synchronize'
        )
      )
      || github.event_name == 'issue_comment'
      && github.event.action == 'created'
      && (
        github.event.comment.body == '/please-review'
        || github.event.comment.body == '/please-check-security'
      )
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Run Bandit security linter
        id: bandit
        run: |
          uvx ruff check --select S --no-fix .
          echo "Security checks: $( (( $? == 0 )) && echo ✅ || echo ❌ )"
