# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Checks that the Docker image is buildable on PRs with relevant changes.

on:
  pull_request:
    types:
      - review_requested
    paths:
      - src/**
      - pyproject.toml
      - Dockerfile
      - .dockerignore

permissions:
  contents: write

jobs:
  check-docker:
    uses: ./.github/workflows/_check-docker.yaml
