# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: check-security
run-name: >
  ${{ github.workflow }} \
  ${{ github.ref_name }} \
  (triggered by ${{ github.ref_type }})

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - edited
    paths:
      - "**/*.py"
      - pyproject.toml
  issue_comment:
    types:
      - created

permissions:
  contents: read
  statuses: write
  actions: read
  security-events: write

jobs:
  security:
    name: Run security linters
    runs-on: ubuntu-latest
    if: >
      (
        github.event_name == 'pull_request'
        && (
          github.event.action == 'ready_for_review'
          || (
            contains(fromJSON('["opened", "edited", "synchronize"]'), github.event.action)
            && (
              !contains(github.event.pull_request, 'draft')
              || github.event.pull_request.draft == false
            )
          )
        )
      ) || (
        github.event_name == 'issue_comment'
        && github.event.action == 'created'
        && contains(fromJSON('["/please-review", "/please-check-security"]'), github.event.comment.body)
      )
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Run Bandit security linter
        id: bandit
        run: |
          uvx ruff check --select S --no-fix .
          echo "Security checks: $( (( $? == 0 )) && echo ✅ || echo ❌ )"
