# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

on:
  pull_request:
    types:
      - review_requested
    paths:
      - src/**/*.py # for API docs
      - docs/**
      - mkdocs.yaml

permissions:
  contents: read

jobs:
  check-docs:
    uses: ./.github/workflows/_check-mkdocs.yaml
