# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Deploys mkdocs documentation to GitHub Pages.

name: deploy-docs
run-name: >
  ${{ github.workflow }}
  ::${{ github.event_name }}
  ::${{ github.ref_type }}:${{ github.ref_name }}

on:
  push:
    tags:
      - '^v\d+\.\d+\.\d+(-(alpha|beta|preview|rc)\d*)?$' # Match most semver-compatible PEP 440.
    paths:
      - "src/**/*.py"
      - docs/
      - pyproject.toml
      - mkdocs.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
      - name: Deploy docs for ${{ github.ref_name }}
        run: |
          uv run --locked mkdocs build --strict
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - uses: actions/deploy-pages@v4
