# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Tests building a Docker image.

name: docker
run-name: >-
  ${{ github.workflow }}
  :: ${{ github.event_name }}
  :: ${{ github.ref_type }}:${{ github.ref_name }}
  :: @${{ github.actor }}

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - edited
    paths:
      - Dockerfile
      - .dockerignore
      - pyproject.toml
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read
  statuses: write
  actions: read
  security-events: write

jobs:
  docker:
    name: Run tests for ${{ matrix.os }}, Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    if: >-
      github.event_name == 'pull_request'
      && (
        github.event.action == 'ready_for_review'
        || github.event.pull_request.draft == false
        && (
          github.event.action == 'opened'
          || github.event.action == 'edited'
          || github.event.action == 'synchronize'
        )
      )
      || (
        github.event_name == 'issue_comment'
        && contains(fromJSON('["created", "edited"]'), github.event.action)
        && (
          github.event.comment.body == '/please-review'
          || github.event.comment.body == '/please-check-docker'
        )
      )
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Build Docker image
        run: |
          if [[ -f Dockerfile ]]; then
            docker build || exit $?
          fi
