# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: docs-modified
run-name: >-
  ${{ github.workflow }}
  :: ${{ github.event_name }}
  :: ${{ github.ref_type }}:${{ github.ref_name }}
  :: @${{ github.actor }}

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - opened
      - edited
    paths:
      - "src/**/*.py"
      - docs/
      - pyproject.toml
      - mkdocs.yaml
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read
  statuses: write
  actions: read

jobs:
  check-docs:
    name: Test building docs
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request'
        && (
          github.event.action == 'ready_for_review'
          || (
            contains(fromJSON('["opened", "edited", "synchronize"]'), github.event.action)
            && (
              !contains(github.event.pull_request, 'draft')
              || github.event.pull_request.draft == false
            )
          )
        )
      ) || (
        github.event_name == 'issue_comment'
        && contains(fromJSON('["created", "edited"]'), github.event.action)
        && contains(fromJSON('["/please-review", "/please-check-docs"]'), github.event.comment.body)
      )
    uses: _check-docs.yaml
