# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: Format PR

on:
  merge_group:
    types:
      - checks_requested

jobs:
  format:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Ruff format
        # Format Python
        run: |
          pip install 'ruff >=0.5.5'
          ruff format .

      - name: Run Prettier
        # for Python projects, we're mostly formatting YAML and Markdown
        run: |
          npm install --global prettier '>=3.0.0'
          prettier --write .

      # Compress images
      - name: Compress Images
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pre-commit hooks
        # do not continue on error because we should already be formatted
        # we're mostly checking the other things, like that shebangs are executable
        run: |
          pre-commit run --all-files

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "style: auto-format" || echo "No changes found."

      - name: Push changes
        if: success() && steps.commit.outputs.commit != ''
        run: |
          # --force should be fine here, too
          git push origin HEAD:${{ github.ref }} --force-with-lease
