# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: format-pr
run-name: >
  ${{ github.workflow }}
  :: ${{ github.event_name }}
  :: ${{ github.ref_type }}:${{ github.ref_name }}
  :: @${{ github.actor }}

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  bump-deps:
    if: >
      contains(fromJSON('["created", "edited"]'), github.event.action)
      && github.event.comment.body == '/please-format'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]' || exit $?
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' || exit $?

      - name: Upgrade the lock file
        id: pre-commit
        run: |
          uv lock --upgrade || exit $?
          if git diff --quiet uv.lock; then
            git commit --no-verify -m "build: update lock file" uv.lock || exit $?
          else
            printf "No changes to uv.lock to commit\n"
          fi

      - name: Upgrade the pre-commit config
        id: pre-commit
        run: |
          uv sync --only-dev || exit $?
          uv run pre-commit install || exit $?
          uv run pre-commit autoupdate || exit $?
          if git diff --quiet .pre-commit-config.yaml; then
            git commit --no-verify -m "ci: upgrade pre-commit config" .pre-commit-config.yaml || exit $?
          else
            printf "No changes to .pre-commit-config.yaml to commit\n"
          fi

      - name: Commit any formatting changes
        run: |
          uv run pre-commit run --all-files || exit $?
          if git diff --quiet .; then
            git commit -m "style: auto-fix lint violations and autoformat" . || exit $?
          else
            printf "No style changes to commit\n"
          fi

      - name: Push changes
        run: |
          git push || exit $?
