# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: format-pr
run-name: >
  ${{ github.workflow }} \
  ${{ github.ref_name }} \
  (triggered by ${{ github.ref_type }})

on:
  merge_group:
    types:
      - checks_requested

jobs:
  format:
    if: >
      github.event_name == 'pull_request'
      && (
        github.event.action == 'ready_for_review'
        || github.event.pull_request.draft == false
        && (
          github.event.action == 'opened'
          || github.event.action == 'edited'
          || github.event.action == 'synchronize'
        )
      )
      || github.event_name == 'issue_comment'
      && github.event.action == 'created'
      && github.event.comment.body == '/please-format'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Run pre-commit hooks
        # Run once to format, etc.
        # Run again to check.
        run: |
          pre-commit run --all-files || true
          pre-commit run --all-files

      # Compress images
      - name: Compress Images
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true # don't commit

      - name: Commit formatting changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "style: auto-format" || echo "No changes found."

      - name: Update UV lock file
        run: |
          uv lock
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add uv.lock
          git commit -m "build: update uv lock file" || echo "No changes found."

      - name: Force-push changes
        if: success() && steps.commit.outputs.commit != ''
        run: |
          # we could use --force-with-lease if --amend -ing
          git push origin HEAD:${{ github.ref }}
