# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

name: format-pr
run-name: >
  ${{ github.workflow }}
  ::${{ github.event_name }}
  ::${{ github.ref_type }}:${{ github.ref_name }}
  ::@${{ github.actor }}

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  format:
    if: >
      contains(fromJSON('["created", "edited"]'), github.event.action)
      && github.event.comment.body == '/please-format'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Run pre-commit hooks
        # Run once to format, etc.; run again to check.
        run: |
          uvx pre-commit run --all-files || true
          uvx pre-commit run --all-files

      - name: Commit formatting changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "style: auto-format" || printf "No changes found.\n"

      - name: Update UV lock file
        run: |
          uv lock
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add uv.lock
          git commit -m "build: update uv lock file" || printf "No changes found.\n"

      - name: Push changes
        if: success() && steps.commit.outputs.commit != ''
        run: |
          git push origin HEAD:${{ github.ref }}
