name: Maintain labels
run-name: ${{ github.workflow }} for ${{ github.event.issue.number }} (run=${{ github.run_id }})

on:
  issues:
    types:
      - opened
      - closed
      - labeled
  pull_request:
    types:
      - opened
      - closed
      - labeled

jobs:

  maintain-labels:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v3
        with:
          token: ${{ secrets.github_token }}

      - name: Add status awaiting triage to new issues
        if: github.event.action == 'opened' && github.event.issue
        run: |
          gh issue add-label ${{ github.event.issue.number }} "status: awaiting triage"

      - name: Remove old status labels when a new one is added
        if: github.event.action == 'labeled' && github.event.label.name =~ 'status:'
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --remove-label "status:ready for dev,status:blocked,status:needs details,status: discarded,status:awaiting triage"
            --add-label ${{ github.event.label.name }}

      - name: Close issues labeld with status discarded
        if: >
          github.event.action == 'labeled'
          && github.event.label.name == 'status: discarded'
          && github.event.issue
        run: >
          gh issue edit \
            ${{ github.event.issue.number }} \
            --state closed \
            --comment "Not planned." \
            --reason "not_planned"

      - name: Set status to discarded to closed issues
        if: >
          github.event.action == 'closed'
          && github.event.issue.state_reason == 'not_planned'
        run: |
          gh issue edit ${{ github.event.issue.number }} \
          --remove-label "status:ready for dev,status:blocked,status:needs details,status:awaiting triage" \
          --add-label "status: discarded"
