# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

# TODO: This workflow may be unnecessary, as well as potentially problematic if synced to Jira.

name: Maintain labels
run-name: >
  ${{ github.workflow }}
  for ${{ github.event.issue.number }}
  (run=${{ github.run_id }})

on:
  issues:
    types:
      - opened
      - closed
      - labeled
  pull_request:
    types:
      - opened
      - closed
      - labeled

jobs:

  maintain-labels:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v3
        with:
          token: ${{ secrets.github_token }}

      - name: Add state awaiting triage to new issues
        if: github.event.action == 'opened' && github.event.issue
        run: |
          gh issue edit \
            ${{ github.event.issue.number }} \
            --add-label "state: awaiting triage"

      - name: Remove old state labels when a new one is added
        if: github.event.action == 'labeled' && github.event.label.name =~ 'state:'
        run: |
          gh issue edit \
            ${{ github.event.issue.number }} \
            --remove-label "state:ready for dev,state:blocked,state:needs details,state: rejected,state:awaiting triage"
            --add-label ${{ github.event.label.name }}

      - name: Close issues labeld with state rejected
        if: >
          github.event.action == 'labeled'
          && github.event.label.name == 'state: rejected'
          && github.event.issue
        run: >
          gh issue edit \
            ${{ github.event.issue.number }} \
            --state closed \
            --comment "Not planned." \
            --reason "not_planned"

      - name: Set state to rejected to closed issues
        if: >
          github.event.action == 'closed'
          && github.event.issue.state_reason == 'not_planned'
        run: |
          gh issue edit \
            ${{ github.event.issue.number }} \
            --remove-label "state:ready for dev,state:blocked,state:needs details,state:awaiting triage" \
            --add-label "state: rejected"
