# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# When a commit is pushed to main or releases/**,
# runs tests and either opens an issue or uploads coverage reports.
name: Main-test
run-name: Test ${{ github.ref_name }} (${{ github.sha }})

on:
  push:
    paths:
      - pyproject.toml
      - src/**/*.py
      - tests/**/*.py
    branches:
      - main
      - master
      - releases/**

concurrency:
  group: ${{ github.workflow }} / ${{ github.ref_name }}
  # More restrictive groups defined on jobs.

permissions:
  contents: read

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      ref: ${{ github.ref }}
      retention-days: 1 # Only to upload coverage reports.
  create-issue:
    if: ${{ failure() }}
    needs: test
    permissions:
      issues: write
    name: Open a GitHub issue if tests failed
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub issue
        env:
          # For historical reasons, the GH CLI uses GH_TOKEN instead of GITHUB_TOKEN
          # https://github.com/github/docs/issues/21930
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "Test failure(s) on $GITHUB_REF_NAME" \
            --body "See: [run #$GITHUB_RUN_ID]($RUN_URL)" \
            --label "type: bug"
  update-codecov:
    if: ${{ success() && env.CODECOV_TOKEN }}
    needs: test
    uses: ./.github/workflows/_update-codecov.yaml
    with:
      ref_name: ${{ github.ref_name }}
    secrets: inherit
  update-coveralls:
    if: ${{ success() && env.COVERALLS_TOKEN }}
    needs: test
    uses: ./.github/workflows/_update-coveralls.yaml
    with:
      ref_name: ${{ github.ref_name }}
    secrets: inherit
