# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Checks that the docs are buildable on PRs with relevant changes.
name: PR-check-docs
run-name: >-
  Check docs on PR ${{ github.event.pull_request.number }}
  by ${{ github.event.pull_request.user.login }}

on:
  pull_request:
    types:
      - review_requested
    paths:
      - docs/**
      - mkdocs.yaml
      - src/**/*.py # for API docs

concurrency:
  group: ${{ github.workflow }} / ${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check-docs:
    uses: ./.github/workflows/_check-docs.yaml
    with:
      ref: ${{ github.ref }}
