# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Checks that the Docker image is buildable on PRs with relevant changes.
name: pr-check-docker
run-name: Check PR ${{ github.event.pull_request.number }} Docker

on:
  pull_request:
    types:
      - review_requested
    paths:
      - src/**
      - pyproject.toml
      - Dockerfile
      - .dockerignore

concurrency:
  group: ${{ github.workflow }} / ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-docker:
    uses: ./.github/workflows/_test-docker.yaml
    with:
      ref: ${{ github.ref }}
