# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Runs tests on PRs with relevant changes.

name: PR-test
run-name: >-
  Test PR ${{ github.event.pull_request.number }}
  by ${{ github.event.pull_request.user.login }}

on:
  pull_request:
    types:
      - review_requested
    paths:
      - src/**
      - tests/**
      - pyproject.toml

concurrency:
  group: ${{ github.workflow }} / ${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-security:
    name: Check security
    uses: ./.github/workflows/_lint.yaml
    with:
      ref: ${{ github.ref }}
      rules: S
  test:
    name: Run PyTest tests
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      ref: ${{ github.ref }}
