# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Runs the release process when `validate` completes successfully (after a tag is pushed).
name: Publish
run-name: >-
  ${{ github.event.workflow_run.conclusion == 'success' && 'Publish' || 'Ignore' }} ${{ github.ref_name }}

on:
  workflow_run:
    types:
      - completed
    workflows:
      - validate

concurrency:
  # Only allow one publish workflow to run at a time.
  # This prevents accidental double-publishes and avoids upsetting external services.
  # There's also little reason to run more than one at a time.
  group: publish
  # DO NOT cancel this workflow if it's already running.

permissions:
  contents: read

jobs:
  accept:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          printf "Accepted %s for release.\n" "${{ github.ref_name }}"
  publish-docs:
    needs: accept
    permissions:
      pages: write
    uses: .github/workflows/_publish-docs.yaml
  publish-github:
    needs: accept
    permissions:
      pages: write
    uses: .github/workflows/_publish-github.yaml
  publish-pypi:
    needs: accept
    uses: .github/workflows/_publish-pypi.yaml
    secrets: inherit
  publish-docker:
    needs: accept
    uses: .github/workflows/_publish-docker.yaml
    secrets: inherit
