# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Runs the release process when `validate` completes successfully (after a tag is pushed).
name: Publish
run-name: >-
  ${{ github.event.workflow_run.conclusion == 'success' && 'Publish' || 'Ignore' }}
  ${{ github.ref_name }}

on:
  workflow_run:
    types:
      - completed
    workflows:
      - validate

concurrency:
  # Only allow one publish workflow to run at a time.
  # This prevents accidental double-publishes and avoids upsetting external services.
  # There's also little reason to run more than one at a time.
  group: ${{ github.workflow }}
  # DO NOT cancel this workflow if it's already running; it's VERY NON-ATOMIC.

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  accept:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Determine whether this is a full release or preview
    runs-on: ubuntu-latest
    outputs:
      is-real-release: ${{ steps.check-ref.outputs.is_real }}
    steps:
      - id: check-ref
        run: |
          # ::tyranno:: regex_1='^refs/tags/$<<~.cicd.tag.release-trigger>>$'
          regex_1='^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$'
          if [[ "$GITHUB_REF" =~ $regex_1 ]]; then
             echo "is_real=true" >> $GITHUB_OUTPUT
          fi
  publish-docs:
    needs: accept
    permissions:
      contents: write
      pages: write
    uses: ./.github/workflows/_publish-docs.yaml
    secrets: inherit
  publish-github:
    needs: accept
    permissions:
      contents: write
    uses: ./.github/workflows/_publish-github.yaml
    secrets: inherit
  publish-pypi:
    needs: accept
    uses: ./.github/workflows/_publish-pypi.yaml
    with:
      repository: ${{ needs.accept.outputs.is-real-release && 'pypi' || 'testpypi' }}
    secrets: inherit
  publish-docker:
    needs: accept
    uses: ./.github/workflows/_publish-docker.yaml
    with:
      push: ${{ needs.accept.outputs.is-real-release }}
    secrets: inherit
