# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        required: true
        description: Pre-release type
        options: [alpha, beta, rc, ""]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  bump:
    name: Bump version and create changelog with commitizen
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - id: cz-release
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          gpg_sign: true
          prerelease: ${{ github.event.inputs.release-type }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [pypi-publish, docker-publish, pages]
    if: ${{ !cancelled() && SLACK_WEBHOOK != '' }}
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job_status }}
          SLACK_LINK_NAMES: true
          MSG_MINIMAL: true
