# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Sends coverage reports when a PR is merged into main.

on:
  push:
    paths:
      - pyproject.toml
      - src/**/*.py
      - tests/**/*.py
    branches:
      - main
      - master

permissions:
  contents: read

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      ref: ${{ github.ref }}
      retention-days: 1
  update-codecov:
    if: ${{ env.CODECOV_TOKEN != '' }}
    uses: ./.github/workflows/_update-codecov.yaml
  update-coveralls:
    if: ${{ env.COVERALLS_TOKEN != '' }}
    uses: ./.github/workflows/_update-coveralls.yaml
