name: Test PR

on:
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - edited
  issue_comment:
    types:
      - created

jobs:
  test:
    name: Test
    if: |
      github.event_name == 'pull_request' &&
        github.event.action == 'ready_for_review' ||
      github.event_name == 'pull_request' &&
        github.event.action == 'synchronize' &&
        github.event.pull_request.draft == false ||
      github.event_name == 'pull_request' &&
        github.event.action == 'edited' &&
        github.event.pull_request.draft == false ||
      github.event_name == 'issue_comment' &&
        github.event.action == 'created'
    uses: ./.github/workflows/_test.yaml
    secrets: inherit
