# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Runs tests on PRs with relevant changes.

on:
  pull_request:
    types:
      - review_requested
    paths:
      - src/**
      - tests/**
      - pyproject.toml

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/_run-pytest.yaml
