# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Verifies that we can start the release process when a tag `v<major>.<minor>.<build>` is pushed.

on:
  push:
    tags:
      # ::tyranno:: - '$<<.cicd.git-release-regex>>'
      - '^v(?P<major>\d+)\.(?P<minor>\d+)\.(?P<micro>\d+)$'

permissions:
  contents: write

jobs:
  check-hooks:
    uses: ./.github/workflows/_check-hooks.yaml
  run-tests:
    uses: ./.github/workflows/_run-pytest.yaml
  check-security:
    uses: ./.github/workflows/_check-ruff.yaml
    with:
      rules: S
  build-dist:
    needs:
      - check-hooks
      - run-tests
      - check-security
    uses: ./.github/workflows/_build_dist.yaml
