name: Commitizen Check and Associated Issue Verification

on:
  pull_request:
    types:
      - ready_for_review
      - edited
  issue_comment:
    types:
      - created

jobs:
  commitizen-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen~=3.27

      - name: Check if comment contains /please-check
        if: github.event_name == 'issue_comment'
        id: check_comment
        run: |
          if [[ "${{ github.event.comment.body }}" == *"/please-check"* ]]; then
            echo "Comment contains /please-check"
          else
            echo "Comment does not contain /please-check"
            exit 0
          fi

      - name: Get linked issues for PR
        if: github.event_name == 'pull_request' || steps.check_comment.outcome == 'success'
        id: get_linked_issues
        run: |
          QUERY='query($repository: String!, $owner: String!, $number: Int!) {
            repository(name: $repository, owner: $owner) {
              pullRequest(number: $number) {
                closingIssuesReferences(first: 100) {
                  totalCount
                  nodes {
                    number
                  }
                }
              }
            }
          }'
          response=$(gh api graphql -f query="$QUERY" -f repository="${{ github.event.repository.name }}" -f owner="${{ github.repository_owner }}" -f number="${{ github.event.pull_request.number }}")
          echo "$response" | jq '.data.repository.pullRequest.closingIssuesReferences.totalCount' > issue_count.txt
          echo "$response" | jq -r '.data.repository.pullRequest.closingIssuesReferences.nodes[].number' > linked_issues.txt

      - name: Check for exactly one linked issue
        if: github.event_name == 'pull_request' || steps.check_comment.outcome == 'success'
        run: |
          issue_count=$(cat issue_count.txt)
          if [[ "$issue_count" -ne 1 ]]; then
            echo "There must be exactly one linked issue. Found $issue_count."
            exit 1
          fi

      - name: Validate commit message with Commitizen
        if: github.event_name == 'pull_request' || steps.check_comment.outcome == 'success'
        run: |
          commit_message=$(jq -r '.pull_request.title' "$GITHUB_EV
