# SPDX-FileCopyrightText: Copyright 2020-2025, Contributors to Tyrannosaurus
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/tyrannosaurus
# SPDX-License-Identifier: Apache-2.0

# Verifies that we can start the release process when a tag `v<major>.<minor>.<build>` is pushed.
name: Validate-release
run-name: >-
  Validate release of ${{ github.ref_name }} (triggered by ${{ github.triggering_actor }})

on:
  push:
    tags:
      # ::tyranno:: - '^$<<~.cicd.trigger.prerelease>>$'
      - '^v[0-9]+\.[0-9]+\.[0-9]+-((alpha|beta|rc)\.)?\d+$'
      # ::tyranno:: - '^$<<~.cicd.trigger.release>>$'
      - '^v[0-9]+\.[0-9]+\.[0-9]+$'

permissions:
  contents: read

concurrency:
  # In contrast, the `publish` workflow uses the constant group `publish`
  # (with `cancel-in-progress` set to FALSE).
  # It's safe to cancel runs of `validate`, but not of `publish`.
  # We'll let runs proceed here, then bottle up against the start of `publish`.
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check-hooks:
    uses: ./.github/workflows/_check-hooks.yaml
    with:
      ref: ${{ github.ref }}
  run-tests:
    uses: ./.github/workflows/_run-pytest.yaml
    with:
      ref: ${{ github.ref }}
  check-security:
    uses: ./.github/workflows/_check-ruff.yaml
    with:
      ref: ${{ github.ref }}
      rules: S
  check-docker:
    uses: ./.github/workflows/_check-docker.yaml
    with:
      ref: ${{ github.ref }}
  build-dist:
    needs:
      - check-hooks
      - run-tests
      - check-security
      - check-docker
    permissions:
      contents: write
    uses: ./.github/workflows/_build_dist.yaml
    with:
      ref: ${{ github.ref }}
      ref_name: ${{ github.ref_name }}
